import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { violations } from '../scripts/check-commit-message.mjs';

test('rejects AI trailers and known English attribution, including Unicode formatting', () => {
  for (const footer of [
    'Co-Authored-By: Claude Sonnet 4 <noreply@anthropic.com>',
    'Co-authored-by: Copilot App <223556219+Copilot@users.noreply.github.com>',
    'Co-authored-by: aider (model) <aider@aider.chat>',
    'Co-authored-by: Cursor <cursoragent@cursor.com>',
    'Co-authored-by: Codex <codex@openai.com>',
    '🤖 Generated with [Claude Code](https://claude.ai/code)',
    'Generated by ChatGPT', 'Created with Gemini', 'Written using Cline',
    'AI-generated implementation', 'aider: update tests',
    'Generated by GPT-4',
    'This commit was generated by Codex',
    'feat: update parser (generated by AI)',
    'feat: update parser — Generated with Claude',
    'Co-authored-by: Clau\u200bde <noreply@anthropic.com>',
    'Ｃｏ－Ａｕｔｈｏｒｅｄ－Ｂｙ: Claude <noreply@anthropic.com>',
  ]) assert.ok(violations('fix: parser\n\n' + footer).length, footer);
});

test('allows product changes, human co-authors, and discussion of attribution removal', () => {
  for (const message of [
    'feat: support Claude Code', 'fix: Codex model selection', 'fix: handle Copilot responses',
    'docs: describe AI attribution filtering', 'fix: remove Generated with Claude footer',
    'fix: parser\n\nCo-authored-by: Alice Example <alice@example.test>',
    'fix: parser\n\nCo-authored-by: Claude Dupont <claude@example.test>',
    'fix: parser\n\nCo-authored-by: Alice Example <alice@anthropic.com>',
    'docs: document AI-generated commit policy',
  ]) assert.deepEqual(violations(message), [], message);
});

test('real Git hook blocks commits; range and receive checks catch bypassed history', t => {
  const dir = mkdtempSync(join(tmpdir(), 'riftjack-commit-policy-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const env = Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith('GIT_')));
  Object.assign(env, { GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_NOSYSTEM: '1' });
  const options = { cwd: dir, env, encoding: 'utf8' };
  const git = (...args) => execFileSync('git', args, { ...options, stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git('init', '-q'); git('config', 'user.name', 'Test User'); git('config', 'user.email', 'test@example.test');
  for (const name of ['.githooks/commit-msg', 'scripts/check-commit-message.mjs', 'scripts/install-git-hooks.mjs']) {
    mkdirSync(join(dir, name.split('/')[0]), { recursive: true });
    copyFileSync(fileURLToPath(new URL('../' + name, import.meta.url)), join(dir, name));
  }
  execFileSync(process.execPath, ['scripts/install-git-hooks.mjs'], options);
  git('commit', '--allow-empty', '-qm', 'Initial human commit');
  const base = git('rev-parse', 'HEAD');
  const bad = 'fix: parser\n\nCo-authored-by: Claude <noreply@anthropic.com>';
  assert.notEqual(spawnSync('git', ['commit', '--allow-empty', '-qm', bad], options).status, 0);
  assert.equal(git('rev-parse', 'HEAD'), base);
  git('commit', '--allow-empty', '--no-verify', '-qm', bad);
  git('commit', '--allow-empty', '-qm', 'fix: ordinary follow-up');
  const head = git('rev-parse', 'HEAD');
  const check = (...args) => spawnSync(process.execPath, ['scripts/check-commit-message.mjs', ...args], options);
  assert.equal(check('--range', `${base}..${head}`).status, 1);
  assert.equal(check('--range', `${head}..${head}`).status, 0);
  assert.equal(check('--all').status, 1);
  const receive = input => spawnSync(process.execPath, ['scripts/check-commit-message.mjs', '--receive'], { ...options, input });
  assert.equal(receive(`${base} ${head} refs/heads/main\n`).status, 1);
  assert.equal(receive(`${'0'.repeat(40)} ${head} refs/heads/new\n`).status, 1);
  assert.equal(receive(`${head} ${'0'.repeat(40)} refs/heads/delete\n`).status, 0);
  assert.equal(receive('invalid input\n').status, 2);
  assert.equal(check('--range', '--all..HEAD').status, 2);
  git('config', '--local', 'core.hooksPath', 'custom-hooks');
  assert.equal(spawnSync(process.execPath, ['scripts/install-git-hooks.mjs'], options).status, 1);
  assert.equal(git('config', 'core.hooksPath'), 'custom-hooks');
  writeFileSync(join(dir, 'message.txt'), 'fix: ordinary change');
  assert.equal(check('--file', 'message.txt').status, 0);
});
