export const MANAGER_HELP = [
  '## Bot Manager · Help',
  'Create bots and Matrix users, edit profiles and manage access. Send commands **in this DM**. Management commands use English, without `!`; replace example names and paths with your own.',
  '### Create a bot',
  '- `create a Codex bot called Builder`\n- `create a Claude bot called Research`\n- `create a Grok bot called Research`',
  'Grok bots use an external worker. Enable `WORKER_PORT` on the connector host first; configure the worker’s folder on its own machine.',
  'Without a folder, bots use the shared `RIFTJACK_WORKSPACE` directory. Initial names allow ASCII letters, digits, spaces, `_` and `-`, up to 48 characters. The limit is **50 accounts**, including the manager.',
  'Accept the new bot’s DM invitation. Send tasks and working files directly to that bot.',
  '### Workspace · owner only',
  '- `create a Codex bot called Website in projects/demo`\n- `create a Claude bot called Reviewer in ~/Projects/My Project`',
  'The folder is **on the connector host**. The manager shows the full path and asks to create a missing folder or use an existing one. The shared default folder also requires confirmation.',
  '- `!approve` or ✅ — proceed.\n- `!deny` or ❌ — cancel creation.\n- Reply in the same chat or thread. A plain “yes” does not approve an action; removing a reaction does not undo your answer.',
  'Quotes are optional, even for paths with spaces. The last ` in ` separates the path from the name. `in projects/demo` is relative to `RIFTJACK_WORKSPACE`; `~` is the connector user’s home directory. Quote paths containing “ in ”: `in "Projects in progress"`. The selected folder survives restarts.',
  '### List bots',
  '- `list bots` — names, types, Matrix IDs and workspaces. Use a Matrix ID to open a DM.',
  '### Model settings · owner or bot creator',
  '- `set model bot Builder to MODEL` — select a model for a Codex or Claude bot.\n- `set reasoning bot Builder to high` — Codex reasoning effort.\n- `set tier bot Builder to default` — Codex service tier.\n- `show settings bot Builder` — effective values and which are inherited.\n- `reset model bot Builder` — inherit the shared model again; also supports `reset reasoning bot` and `reset tier bot`.',
  'Use a bot name or Matrix ID; quote names containing “ to ”. Settings persist and apply to the next task without restarting or resetting the conversation. Running tasks keep their settings. Model and option availability depends on the CLI and account. Grok settings belong to its external worker.',
  '### Name and avatar',
  '- `rename bot Codex to Riftjack Codex` — change the display name.\n- `set avatar Riftjack Codex` — use as the caption of a PNG, JPEG, GIF or WebP image.\n- `remove avatar Riftjack Codex` — remove the avatar.',
  'Available to **the owner or bot creator**; only the owner can change the manager’s profile. New display names allow Unicode, up to 100 characters.',
  'Select a bot by its case-insensitive name, short ID (`bot_codex_codex`, `@bot`, `bot`) or full `@bot:server` from `list bots`. Names with spaces work; quote an old name containing “ to ”. If several bots match, the manager lists them and asks for the full ID.',
  'Changes apply immediately. The Matrix ID, history and workspace stay the same. **Avatars are visible in the Matrix profile**, beyond the encrypted chat.',
  '### Create a user · owner only',
  '- `create user alice` — create a regular Matrix user.\n- `create user alice named Alice` — set a display name.',
  'Use a username without `@` or a server: 1–64 lowercase ASCII letters, digits, `.`, `_`, `=`, `-`; start with a letter or digit.',
  'The manager asks you to confirm the specific Matrix ID with ✅ or `!approve`; ❌ or `!deny` cancels. A generated password is sent to this encrypted DM. Change it after signing in through Element X.',
  'New users have **no administrator privileges**. Grant bot access separately. This command does not modify existing accounts or reset their passwords.',
  '### Shared access',
  '- `list accounts` — users with shared access.\n- `allow @user:server` — grant access to all bots and the manager.\n- `remove @user:server` — revoke all access, including per-bot lists.',
  '**Only the owner** can change access. Provide a full Matrix ID. Shared access allows creating bots in the shared folder; `allow` alone does not send invitations. `remove` stops the user’s active tasks but does not delete Matrix accounts or bots.',
  '### Access to one bot · owner only',
  '- `allow bot Riftjack Codex for @alice:server @bob:server` — add users.\n- `remove bot Riftjack Codex for @alice:server` — remove from this bot’s list.\n- `list access bot Riftjack Codex` — show per-bot and shared access lists.',
  'Select the bot by name, short ID or full ID. Quote names containing “ for ”. Separate full user Matrix IDs with spaces or commas.',
  'After `allow bot`, the bot invites each user to a separate encrypted DM. Accept in Element X. Repeating the command reuses an existing room or pending invitation.',
  'If the bot is disconnected or an invitation fails, access is retained and the manager reports the result. Retry `allow bot` or open a DM manually. If room creation has an unknown outcome, check existing rooms first; automatic retry is blocked.',
  'Per-bot access grants access **only to the selected Codex, Claude or Grok bot**, without the manager or bot creation. Shared `allow` is not needed. To narrow existing shared access, first use `remove @user:server`, then grant per-bot access.',
  'Access changes apply immediately and survive restarts and renaming. Revoking per-bot access stops the user’s task only on that bot. The owner always has access.',
  '### Controls and restart',
  '- `!help` — show help.\n- `!cancel` — cancel the current operation; completed changes remain.\n- `!restart` — restart all bots.\n- `!restart supervisor` — also restart the supervisor process.',
  'Restarts are **owner only**, with no active tasks. The startup notice returns to the same chat.',
  '---',
  '“Owner” means the initial connector owner. You can copy commands and examples directly from this message.',
].join('\n\n');
